AssetTracking/AssetTracking/Controllers/DetailCategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AssetTracking.BLL;
using AssetTracking.Models.Models;
using AssetTracking.Models.Database;

namespace AssetTracking.Controllers
{
    public class DetailCategoryController : Controller
    {
        private AssetTrackDbContext db = new AssetTrackDbContext();
        private DetailCategoryManager _detailCategoryManager;
        private SubCategoryManager _subCategoryManager;
        private GeneralCategoryManager _generalCategoryManager;

        public DetailCategoryController()
        {
            _subCategoryManager = new SubCategoryManager();
            _detailCategoryManager = new DetailCategoryManager();
            _generalCategoryManager = new GeneralCategoryManager();
        }

        // GET: /DetailCategory/
        public ActionResult Index()
        {
            //var detailcategories = db.DetailCategories.Include(d => d.SubCategory);

            
            var detailcategories = _detailCategoryManager.GetAll();
            return View(detailcategories.ToList());
        }

        // GET: /DetailCategory/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DetailCategory detailcategory = _detailCategoryManager.GetById((int) id);
            if (detailcategory == null)
            {
                return HttpNotFound();
            }
            return View(detailcategory);
        }

        // GET: /DetailCategory/Create
        public ActionResult Create()
        {
            var gCategories = _generalCategoryManager.GetAll();
            ViewBag.generalCategoryID = new SelectList(gCategories, "GeneralCategoryID", "GeneralCategoryName");
            var subCategories = _subCategoryManager.GetAll();
            ViewBag.SubCategoryID = new SelectList(subCategories, "SubCategoryID", "SubCategoryName");
            return View();
        }

        // POST: /DetailCategory/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="DetailCategoryID,SubCategoryID,DetailCategoryName,DetailCategoryCode,DetailCategoryDescription")] DetailCategory detailcategory)
        {
            if (ModelState.IsValid)
            {
                _detailCategoryManager.Add(detailcategory);
                return RedirectToAction("Index");
            }

            var subCategories = _subCategoryManager.GetAll();
            ViewBag.SubCategoryID = new SelectList(subCategories, "SubCategoryID", "SubCategoryName");
            return View(detailcategory);
        }

        // GET: /DetailCategory/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DetailCategory detailcategory = _detailCategoryManager.GetById((int)id);
            if (detailcategory == null)
            {
                return HttpNotFound();
            }
            var subCategories = _subCategoryManager.GetAll();
            ViewBag.SubCategoryID = new SelectList(subCategories, "SubCategoryID", "SubCategoryName");
            return View(detailcategory);
        }

        // POST: /DetailCategory/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="DetailCategoryID,SubCategoryID,DetailCategoryName,DetailCategoryCode,DetailCategoryDescription")] DetailCategory detailcategory)
        {
            if (ModelState.IsValid)
            {
                _detailCategoryManager.Update(detailcategory);
                return RedirectToAction("Index");
            }
            var subCategories = _subCategoryManager.GetAll();
            ViewBag.SubCategoryID = new SelectList(subCategories, "SubCategoryID", "SubCategoryName");
            return View(detailcategory);
        }

        // GET: /DetailCategory/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DetailCategory detailcategory = _detailCategoryManager.GetById((int)id);
            if (detailcategory == null)
            {
                return HttpNotFound();
            }
            return View(detailcategory);
        }

        // POST: /DetailCategory/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _detailCategoryManager.Remove(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AssetTracking/AssetTracking/Views/DetailCategory/Create.cshtml
@model AssetTracking.Models.Models.DetailCategory

@{
    ViewBag.Title = "Create Detail Category";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!-- BEGIN FORM DESIGN -->
<div class="portlet box green">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i>Create Category Detail
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse"> </a>
            <a href="#portlet-config" data-toggle="modal" class="config"> </a>
            <a href="javascript:;" class="reload"> </a>
            <a href="javascript:;" class="remove"> </a>
        </div>
    </div>
    <div class="portlet-body form">
        <!-- BEGIN FORM-->
        @using (Html.BeginForm("Create", "DetailCategory", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()
            <div class="form-body">
                <div class="form-group">
                    <label class="col-md-3 control-label">general Category</label>
                    <div class="col-md-4">
                        @Html.ValidationSummary(true)
                        <div class="input-group">
                            <span class="input-group-addon input-circle-left">
                                <i class="fa fa-building-o" aria-hidden="true"></i>
                            </span>

                            @Html.DropDownList("GeneralCategoryID", ViewBag.generalCategoryID as SelectList, "Select General Category", htmlAttributes: new {@class = "form-control input-circle-right"})
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-body">
                <div class="form-group">
                    <label class="col-md-3 control-label">Category</label>
                    <div class="col-md-4">
                        @Html.ValidationSummary(true)
                        <div class="input-group">
                            <span class="input-group-addon input-circle-left">
                                <i class="fa fa-building-o" aria-hidden="true"></i>
                            </span>
                            @Html.DropDownList("CategoryID", new SelectList(new List<SelectListItem>()), "Select Category", htmlAttributes: new { @class = "form-control input-circle-right" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-body">
                <div class="form-group">
                    <label class="col-md-3 control-label">Sub Category</label>
                    <div class="col-md-4">
                        <div class="input-group">
                            <span class="input-group-addon input-circle-left">
                                <i class="fa fa-building" aria-hidden="true"></i>
                            </span>
                            @Html.DropDownList("SubCategoryID", ViewBag.SubCategoryID as SelectList, "Select Sub-Category", htmlAttributes: new { @class = "form-control input-circle-right" })
                        </div>
                        @Html.ValidationMessageFor(model => model.SubCategoryID, String.Empty, new { @class = "font-red-thunderbird" })

                    </div>
                </div>
            </div>
            <div class="form-body">
                <div class="form-group">
                    <label class="col-md-3 control-label">Detail Category Name</label>
                    <div class="col-md-4">
                        <div class="input-group">
                            <span class="input-group-addon input-circle-left">
                                <i class="fa fa-font" aria-hidden="true"></i>
                            </span>
                            @Html.TextBoxFor(model => model.DetailCategoryName, new { @class = "form-control input-circle-right", @placeholder = "Enter Detail Category Name" })
                        </div>
                        @Html.ValidationMessageFor(model => model.DetailCategoryName, String.Empty, new { @class = "font-red-thunderbird" })
                    </div>
                </div>
            </div>
            <div class="form-body">
                <div class="form-group">
                    <label class="col-md-3 control-label">Detail Category Code</label>
                    <div class="col-md-4">
                        <div class="input-group">
                            <span class="input-group-addon input-circle-left">
                                <i class="fa fa-font" aria-hidden="true"></i>
                            </span>
                            @Html.TextBoxFor(model => model.DetailCategoryCode, new { @class = "form-control input-circle-right", @placeholder = "Enter Detail Category Code" })
                        </div>
                        @Html.ValidationMessageFor(model => model.DetailCategoryCode, String.Empty, new { @class = "font-red-thunderbird" })
                    </div>
                </div>
            </div>
            <div class="form-body">
                <div class="form-group">
                    <label class="col-md-3 control-label">Detail Category Description</label>
                    <div class="col-md-4">
                        <div class="input-group">
                            <span class="input-group-addon input-circle-left">
                                <i class="fa fa-font" aria-hidden="true"></i>
                            </span>
                            @Html.TextBoxFor(model => model.DetailCategoryDescription, new { @class = "form-control input-circle-right", @placeholder = "Enter Detail Category Description" })
                        </div>
                        @Html.ValidationMessageFor(model => model.DetailCategoryDescription, String.Empty, new { @class = "font-red-thunderbird" })
                    </div>
                </div>
            </div>
            <div class="form-actions">
                <div class="row">
                    <div class="col-md-offset-3 col-md-9">
                        <button type="submit" class="btn btn-circle green">Create</button>
                        @Html.ActionLink("Cancel", "Index", "DetailCategory", null, new { @type = "button", @class = "btn btn-circle grey-salsa btn-outline" })
                    </div>
                </div>
            </div>
        }
        <!-- END FORM-->
    </div>
</div>

@section scripts{
    <script src="~/Scripts/SubCategory/Create.js"></script>
}

AssetTracking/AssetTracking/Views/DetailCategory/Delete.cshtml
@model AssetTracking.Models.Models.DetailCategory

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DetailCategory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SubCategory.SubCategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubCategory.SubCategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DetailCategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DetailCategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DetailCategoryCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DetailCategoryCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DetailCategoryDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DetailCategoryDescription)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AssetTracking/AssetTracking/Views/DetailCategory/Details.cshtml
@model AssetTracking.Models.Models.DetailCategory

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>DetailCategory</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SubCategory.SubCategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubCategory.SubCategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DetailCategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DetailCategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DetailCategoryCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DetailCategoryCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DetailCategoryDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DetailCategoryDescription)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.DetailCategoryID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AssetTracking/AssetTracking/Views/DetailCategory/Edit.cshtml
@model AssetTracking.Models.Models.DetailCategory

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DetailCategory</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.DetailCategoryID)

        <div class="form-group">
            @Html.LabelFor(model => model.SubCategoryID, "SubCategoryID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SubCategoryID", String.Empty)
                @Html.ValidationMessageFor(model => model.SubCategoryID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DetailCategoryName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DetailCategoryName)
                @Html.ValidationMessageFor(model => model.DetailCategoryName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DetailCategoryCode, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DetailCategoryCode)
                @Html.ValidationMessageFor(model => model.DetailCategoryCode)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DetailCategoryDescription, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DetailCategoryDescription)
                @Html.ValidationMessageFor(model => model.DetailCategoryDescription)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AssetTracking/AssetTracking/Views/DetailCategory/Index.cshtml
@model IEnumerable<AssetTracking.Models.Models.DetailCategory>

@{
    ViewBag.Title = "Category Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <!-- BEGIN TABLE PORTLET-->
        <div class="portlet box green">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-comments"></i>Category Detail Index
                </div>
                <div class="tools">
                    <a href="javascript:;" class="collapse"> </a>
                    <a href="#portlet-config" data-toggle="modal" class="config"> </a>
                    <a href="javascript:;" class="reload"> </a>
                    <a href="javascript:;" class="remove"> </a>
                </div>
            </div>
            <div class="portlet-body">
                <p>
                    @Html.ActionLink("Create New", "Create", "DetailCategory", null, new { @class = "btn btn-sm green-jungle" })
                </p>
                <div class="table-scrollable">
                    <table id="dataTablefunction" class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.SubCategory.SubCategoryName)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.DetailCategoryName)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.DetailCategoryCode)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.DetailCategoryDescription)
                                </th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.SubCategory.SubCategoryName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.DetailCategoryName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.DetailCategoryCode)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.DetailCategoryDescription)
                                    </td>
                                    <td>
                                        @Html.ActionLink("Edit", "Edit", "DetailCategory", new { id = item.DetailCategoryID }, new { @class = "label label-sm label-info" }) |
                                        @Html.ActionLink("Details", "Details", "DetailCategory", new { id = item.DetailCategoryID }, new { @class = "label label-sm label-warning" }) |
                                        @Html.ActionLink("Delete", "Delete", "DetailCategory", new { id = item.DetailCategoryID }, new { @class = "label label-sm label-danger" })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- END TABLE PORTLET-->
    </div>
</div>
@section scripts{
    <script src="~/Scripts/DT.js"></script>
}