AssetTracking/AssetTracking/Controllers/DesignationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AssetTracking.BLL;
using AssetTracking.Models.Models;
using AssetTracking.Models.Database;
using AssetTracking.Models.Interfaces.IModelManager;
using AssetTracking.Models.Interfaces.IModelRepository;

namespace AssetTracking.Controllers
{
    public class DesignationController : Controller
    {
        private IDesignationManager _designationManager;

        public DesignationController()
        {
           _designationManager = new DesignationManager();
        }
        // GET: /Designation/
        public ActionResult Index()
        {
            var designation = _designationManager.GetAll();
            return View(designation.ToList());
        }

        // GET: /Designation/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Designation designation = _designationManager.GetById((int) id);
            if (designation == null)
            {
                return HttpNotFound();
            }
            return View(designation);
        }

        // GET: /Designation/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Designation/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="DesignationID,DesignationName")] Designation designation)
        {
            if (ModelState.IsValid)
            {
                //db.Designations.Add(designation);
                //db.SaveChanges();
                _designationManager.Add(designation);
                return RedirectToAction("Index");
            }

            return View(designation);
        }

        // GET: /Designation/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Designation designation = _designationManager.GetById((int) id);
            if (designation == null)
            {
                return HttpNotFound();
            }
            return View(designation);
        }

        // POST: /Designation/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="DesignationID,DesignationName")] Designation designation)
        {
            if (ModelState.IsValid)
            {
                _designationManager.Update(designation);
                return RedirectToAction("Index");
            }
            return View(designation);
        }

        // GET: /Designation/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Designation designation = _designationManager.GetById((int)id);
            if (designation == null)
            {
                return HttpNotFound();
            }
            return View(designation);
        }

        // POST: /Designation/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _designationManager.Remove(id);
            //db.Designations.Remove(designation);
            //db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                //db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AssetTracking/AssetTracking/Views/Designation/Create.cshtml
@model AssetTracking.Models.Models.Designation

@{
    ViewBag.Title = "Create Designation";
}

<!-- BEGIN FORM DESIGN -->
<div class="portlet box green">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i>Create Designation
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse"> </a>
            <a href="#portlet-config" data-toggle="modal" class="config"> </a>
            <a href="javascript:;" class="reload"> </a>
            <a href="javascript:;" class="remove"> </a>
        </div>
    </div>
    <div class="portlet-body form">
        <!-- BEGIN FORM-->
        @using (Html.BeginForm("Create", "Designation", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()
            <div class="form-body">
                <div class="form-group">
                    <label class="col-md-3 control-label">Designation Name</label>
                    <div class="col-md-4">
                        <div class="input-group">
                            <span class="input-group-addon input-circle-left">
                                <i class="fa fa-font" aria-hidden="true"></i>
                            </span>
                            @Html.TextBoxFor(model => model.DesignationName, new { @class = "form-control input-circle-right", @placeholder = "Enter Designation Name" })
                        </div>
                        @Html.ValidationMessageFor(model => model.DesignationName, String.Empty, new { @class = "font-red-thunderbird" })
                    </div>
                </div>
            </div>
            <div class="form-actions">
                <div class="row">
                    <div class="col-md-offset-3 col-md-9">
                        <button type="submit" class="btn btn-circle green">Create</button>
                        @Html.ActionLink("Cancel", "Index", "Designation", null, new { @type = "button", @class = "btn btn-circle grey-salsa btn-outline" })
                    </div>
                </div>
            </div>
        }
        <!-- END FORM-->
    </div>
</div>

AssetTracking/AssetTracking/Views/Designation/Delete.cshtml
@model AssetTracking.Models.Models.Designation

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Designation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DesignationName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DesignationName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AssetTracking/AssetTracking/Views/Designation/Details.cshtml
@model AssetTracking.Models.Models.Designation

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Designation</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DesignationName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DesignationName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.DesignationID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AssetTracking/AssetTracking/Views/Designation/Edit.cshtml
@model AssetTracking.Models.Models.Designation

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Designation</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.DesignationID)

        <div class="form-group">
            @Html.LabelFor(model => model.DesignationName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DesignationName)
                @Html.ValidationMessageFor(model => model.DesignationName)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AssetTracking/AssetTracking/Views/Designation/Index.cshtml
@model IEnumerable<AssetTracking.Models.Models.Designation>

@{
    ViewBag.Title = "Designation";
}

<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PORTLET-->
        <div class="portlet box green">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-comments"></i>Designation Index
                </div>
                <div class="tools">
                    <a href="javascript:;" class="collapse"> </a>
                    <a href="#portlet-config" data-toggle="modal" class="config"> </a>
                    <a href="javascript:;" class="reload"> </a>
                    <a href="javascript:;" class="remove"> </a>
                </div>
            </div>
            <div class="portlet-body">
                <p>
                    @Html.ActionLink("Create New", "Create", "Designation", null, new { @class = "btn btn-sm green-jungle" })
                </p>
                <div class="table-scrollable">
                    <table id="dataTablefunction" class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.DesignationName)
                                </th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.DesignationName)
                                    </td>
                                    <td>
                                        @Html.ActionLink("Edit", "Edit", "Designation", new { id = item.DesignationID }, new { @class = "label label-sm label-info" }) |
                                        @Html.ActionLink("Details", "Details", "Designation", new { id = item.DesignationID }, new { @class = "label label-sm label-warning" }) |
                                        @Html.ActionLink("Delete", "Delete", "Designation", new { id = item.DesignationID }, new { @class = "label label-sm label-danger" })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- END PORTLET-->
    </div>
</div>
@section scripts{
    <script src="~/Scripts/DT.js"></script>
}