AssetTracking/AssetTracking/Controllers/GeneralCategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AssetTracking.BLL;
using AssetTracking.Models.Models;
using AssetTracking.Models.Database;

namespace AssetTracking.Controllers
{
    public class GeneralCategoryController : Controller
    {
        private AssetTrackDbContext db = new AssetTrackDbContext();
        private GeneralCategoryManager _generalCategoryManager;
        private CategoryManager _categoryManager;

        public GeneralCategoryController()
        {
            _generalCategoryManager= new GeneralCategoryManager();
            _categoryManager = new CategoryManager();
        }
        // GET: /GeneralCategory/
        public ActionResult Index()
        {
            var GeneralCategories = _generalCategoryManager.GetAll();
            return View(GeneralCategories.ToList());
        }

        // GET: /GeneralCategory/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GeneralCategory generalcategory = _generalCategoryManager.GetById((int) id);
            if (generalcategory == null)
            {
                return HttpNotFound();
            }
            return View(generalcategory);
        }

        // GET: /GeneralCategory/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /GeneralCategory/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="GeneralCategoryID,GeneralCategoryName,GeneralCategoryCode")] GeneralCategory generalcategory)
        {
            if (ModelState.IsValid)
            {
                //db.GeneralCategories.Add(generalcategory);
                //db.SaveChanges();
                _generalCategoryManager.Add(generalcategory);
                return RedirectToAction("Index");
            }

            return View(generalcategory);
        }

        // GET: /GeneralCategory/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GeneralCategory generalcategory = _generalCategoryManager.GetById((int) id);
            if (generalcategory == null)
            {
                return HttpNotFound();
            }
            return View(generalcategory);
        }

        // POST: /GeneralCategory/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="GeneralCategoryID,GeneralCategoryName,GeneralCategoryCode")] GeneralCategory generalcategory)
        {
            if (ModelState.IsValid)
            {
                //db.Entry(generalcategory).State = EntityState.Modified;
                //db.SaveChanges();
                _generalCategoryManager.Update(generalcategory);
                return RedirectToAction("Index");
            }
            return View(generalcategory);
        }

        // GET: /GeneralCategory/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GeneralCategory generalcategory = _generalCategoryManager.GetById((int) id);
            if (generalcategory == null)
            {
                return HttpNotFound();
            }
            return View(generalcategory);
        }

        // POST: /GeneralCategory/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
             _generalCategoryManager.Remove(id);
            //db.GeneralCategories.Remove(generalcategory);
            //db.SaveChanges();
            return RedirectToAction("Index");
        }

        public JsonResult GetCategoryByGeneralCategory(long generalcategoryId)
        {
            var category = _categoryManager.GetCategorysByGeneralCateogry(generalcategoryId);
            var categoryJsonData = category.Select(
                c => new
                {
                    c.GeneralCategoryID,
                    c.CategoryName,
                    c.CategoryCode,
                    c.CategoryDescription,
                    c.CategoryID,
                    c.SubCategories
                });
            return Json(categoryJsonData, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                //db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AssetTracking/AssetTracking/Views/GeneralCategory/Create.cshtml
@model AssetTracking.Models.Models.GeneralCategory

@{
    ViewBag.Title = "Create General Category";
}

  <!-- BEGIN FORM DESIGN -->
<div class="portlet box green">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i>Create General Category
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse"> </a>
            <a href="#portlet-config" data-toggle="modal" class="config"> </a>
            <a href="javascript:;" class="reload"> </a>
            <a href="javascript:;" class="remove"> </a>
        </div>
    </div>
    <div class="portlet-body form">

        <!-- BEGIN FORM-->
        @using (Html.BeginForm("Create", "GeneralCategory", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()
            <div class="form-body">
                <div class="form-group">
                    <label class="col-md-3 control-label">General Category Name</label>
                    <div class="col-md-4">
                        <div class="input-group">
                            <span class="input-group-addon input-circle-left">
                                <i class="fa fa-building" aria-hidden="true"></i>
                            </span>
                            @Html.TextBoxFor(model => model.GeneralCategoryName, new { @placeholder = "Enter General Category Name", @class = " form-control input-circle-right" })
                        </div>
                        @Html.ValidationMessageFor(model => model.GeneralCategoryName, String.Empty, new { @class = "font-red-thunderbird" })
                    </div>
                </div>
            </div>
            <div class="form-body">
                <div class="form-group">
                    <label class="col-md-3 control-label">General Category Code</label>
                    <div class="col-md-4">
                        <div class="input-group">
                            <span class="input-group-addon input-circle-left">
                                <i class="fa fa-building" aria-hidden="true"></i>
                            </span>
                            @Html.TextBoxFor(model => model.GeneralCategoryCode, new { @placeholder = "Enter General Category Code", @class = " form-control input-circle-right" })
                        </div>
                        @Html.ValidationMessageFor(model => model.GeneralCategoryCode, String.Empty, new { @class = "font-red-thunderbird" })
                    </div>
                </div>
            </div>
            <div class="form-actions">
                <div class="row">
                    <div class="col-md-offset-3 col-md-9">
                        <button type="submit" class="btn btn-circle green">Create</button>
                        @Html.ActionLink("Cancel", "Index", "GeneralCategory", null, new { @type = "button", @class = "btn btn-circle grey-salsa btn-outline" })
                    </div>
                </div>
            </div>
        }
        <!-- END FORM-->
    </div>
</div>

AssetTracking/AssetTracking/Views/GeneralCategory/Delete.cshtml
@model AssetTracking.Models.Models.GeneralCategory

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>GeneralCategory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GeneralCategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GeneralCategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GeneralCategoryCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GeneralCategoryCode)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AssetTracking/AssetTracking/Views/GeneralCategory/Details.cshtml
@model AssetTracking.Models.Models.GeneralCategory

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>GeneralCategory</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GeneralCategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GeneralCategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GeneralCategoryCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GeneralCategoryCode)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.GeneralCategoryID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AssetTracking/AssetTracking/Views/GeneralCategory/Edit.cshtml
@model AssetTracking.Models.Models.GeneralCategory

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>GeneralCategory</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.GeneralCategoryID)

        <div class="form-group">
            @Html.LabelFor(model => model.GeneralCategoryName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GeneralCategoryName)
                @Html.ValidationMessageFor(model => model.GeneralCategoryName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GeneralCategoryCode, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GeneralCategoryCode)
                @Html.ValidationMessageFor(model => model.GeneralCategoryCode)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AssetTracking/AssetTracking/Views/GeneralCategory/Index.cshtml
@model IEnumerable<AssetTracking.Models.Models.GeneralCategory>

@{
    ViewBag.Title = "General Category";
}

<div class="row">
    <div class="col-md-12">
        <!-- BEGIN TABLE PORTLET-->
        <div class="portlet box green">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-comments"></i>General Category Index
                </div>
                <div class="tools">
                    <a href="javascript:;" class="collapse"> </a>
                    <a href="#portlet-config" data-toggle="modal" class="config"> </a>
                    <a href="javascript:;" class="reload"> </a>
                    <a href="javascript:;" class="remove"> </a>
                </div>
            </div>
            <div class="portlet-body">
                <p>
                    @Html.ActionLink("Create New", "Create", "GeneralCategory", null, new { @class = "btn btn-sm green-jungle" })
                </p>
                <div class="table-scrollable">
                    <table id="dataTablefunction" class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.GeneralCategoryName)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.GeneralCategoryCode)
                                </th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.GeneralCategoryName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.GeneralCategoryCode)
                                    </td>
                                    <td>
                                        @Html.ActionLink("Edit", "Edit", "GeneralCategory", new { id = item.GeneralCategoryID }, new { @class = "label label-sm label-info" }) |
                                        @Html.ActionLink("Details", "Details", "GeneralCategory", new { id = item.GeneralCategoryID }, new { @class = "label label-sm label-warning" }) |
                                        @Html.ActionLink("Delete", "Delete", "GeneralCategory", new { id = item.GeneralCategoryID }, new { @class = "label label-sm label-danger" })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- END TABLE PORTLET-->
    </div>
</div>
@section scripts{
    <script src="~/Scripts/DT.js"></script>
}